# Generated by Django 3.2.5 on 2021-07-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metodos',
            fields=[
                ('MetodoId', models.AutoField(primary_key=True, serialize=False)),
                ('MetodoNombre', models.CharField(max_length=256)),
                ('MetodoDescripcion', models.CharField(max_length=515)),
                ('MetodoMecanismo', models.CharField(max_length=512)),
                ('MetodoImagen', models.CharField(max_length=128)),
            ],
        ),
    ]
