# Generated by Django 3.2.5 on 2021-08-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetodoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anticoncepcion',
            fields=[
                ('AnticoncepcionID', models.AutoField(primary_key=True, serialize=False)),
                ('AnticoncepcionMes', models.CharField(max_length=100)),
                ('AnticoncepcionDepartamento', models.CharField(max_length=100)),
                ('AnticoncepcionProvincia', models.CharField(max_length=256)),
                ('AnticoncepcionDistrito', models.CharField(max_length=256)),
                ('AnticoncepcionEdad', models.CharField(max_length=20)),
                ('AnticoncepcionMetodo', models.CharField(max_length=50)),
            ],
        ),
    ]
